# Use e.g. for Kueue labels,
labels: {}
# Example:
# labels:
#   amd.com/label: 123

# Which model to download
modelID:
modelRevision:

# Data download and preprocess script:
# This needs to be a text block of a script that downloads and preprocesses data to the /downloads/datasets/ directory.
dataScript:
# Example:
# dataScript: |
#   import datasets
#   dataset = datasets.load_dataset("HuggingFaceH4/ultrachat_200k", split="train_sft")
#   dataset.to_json("/downloads/datasets/ultrachat_200k_train.jsonl") # Need to save any data files in this specific directory to be uploaded.

# Where the resources should be stored:
bucketModelPath:
bucketDataDir:
bucketStorageHost:

# Download & Upload configuration:
downloadExcludeGlob: "original/*"  # Exclude things from the HuggingFace download with this
allowOverwrite: false

# Bucket credentials from a secret:
bucketCredentialsSecret:
  name:
  accessKeyKey:
  secretKeyKey:

# Storage configuration:
storageClass:
storageQuantity: "10Gi"