metadata:
  labels:
    pipeline_tag: "text-generation"
    chat: "true"

model: "CohereForAI/aya-expanse-32b"
served_model_name: "CohereForAI/aya-expanse-32b"

env_vars:
  HF_TOKEN:
    key: hf-token
    name: hf-token
