metadata:
  labels:
    pipeline_tag: "text-generation"
    chat: "true"

model: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B"

vllm_engine_args:
  gpu-memory-utilization: "0.95"
  max-model-len: "65536"
