metadata:
  labels:
    pipeline_tag: "text-generation"
    chat: "true"

image: "rocm/vllm:rocm6.3.1_vllm_0.8.5_20250513"
model: "deepseek-ai/DeepSeek-V3"
gpus: 8
memory_per_gpu: 64 # Gi
cpu_per_gpu: 4

vllm_engine_args:
  max-model-len: "32768"

storage:
  ephemeral:
    quantity: 1024Gi
    storageClassName: mlstorage
    accessModes:
      - ReadWriteOnce
  dshm:
    sizeLimit: 64Gi
