metadata:
  labels:
    pipeline_tag: "text-generation"
    chat: "true"

image: "rocm/vllm:rocm6.3.1_vllm_0.8.5_20250513"
model: "google/gemma-3-1b-it"

env_vars:
  HF_TOKEN:
    key: hf-token
    name: hf-token
  VLLM_USE_V1: "1"
