metadata:
  labels:
    pipeline_tag: "text-generation"
    chat: "false"

model: "meta-llama/Llama-3.1-70B"

vllm_engine_args:
  gpu-memory-utilization: "0.95"
  max-model-len: "65536"

env_vars:
  HF_TOKEN:
    key: hf-token
    name: hf-token

storage:
  ephemeral:
    quantity: 256Gi
    storageClassName: mlstorage
    accessModes:
      - ReadWriteOnce
