metadata:
  labels:
    pipeline_tag: "text-generation"
    chat: "true"

model: "meta-llama/Llama-3.1-8B-Instruct"
served_model_name: "meta-llama/Llama-3.1-8B-Instruct"

env_vars:
  HF_TOKEN:
    key: hf-token
    name: hf-token
