metadata:
  labels:
    pipeline_tag: "image-text-to-text"
    chat: "true"

model: "meta-llama/Llama-3.2-11B-Vision-Instruct"
served_model_name: "meta-llama/Llama-3.2-11B-Vision-Instruct"

env_vars:
  HF_TOKEN:
    key: hf-token
    name: hf-token
