metadata:
  labels:
    pipeline_tag: "text-generation"
    chat: "true"

model: "mistralai/Mixtral-8x22B-Instruct-v0.1"
served_model_name: "mistralai/Mixtral-8x22B-Instruct-v0.1"
gpus: 4

env_vars:
  HF_TOKEN:
    key: hf-token
    name: hf-token

storage:
  ephemeral:
    quantity: 300Gi
    storageClassName: mlstorage
    accessModes:
      - ReadWriteOnce
