metadata:
  labels:
    pipeline_tag: "text-generation"
    chat: "true"

image: "rocm/vllm:rocm6.3.1_vllm_0.8.5_20250513"
model: "Qwen/Qwen3-235B-A22B"
gpus: 4
memory_per_gpu: 64 # Gi
cpu_per_gpu: 4

storage:
  ephemeral:
    quantity: 512Gi
    storageClassName: mlstorage
    accessModes:
      - ReadWriteOnce
  dshm:
    sizeLimit: 64Gi
