metadata:
  labels:
    pipeline_tag: "image-text-to-text"
    chat: "true"

image: "rocm/vllm:rocm6.3.1_vllm_0.8.5_20250513"
model: "unsloth/Llama-3.2-90B-Vision-Instruct"
gpus: 4
memory_per_gpu: 64 # Gi
cpu_per_gpu: 4
