apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release.fullname" . }}
  labels:
    app: {{ include "release.fullname" . }}
    {{- range $key, $value := .Values.metadata.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "release.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "release.fullname" . }}
    spec:
      containers:
        - env:
            - name: OPENAI_API_BASE_URLS_K8S
              value: {{ tpl .Values.openai_api_base_urls . | trim | quote -}}
            {{- include "container.env" . | nindent 12 }}
          image: {{ .Values.image | quote}}
          imagePullPolicy: {{ default "Always" .Values.imagePullPolicy | quote }}
          name: {{ .Chart.Name }}
          {{- if .Values.entrypoint }}
          command: ["sh", "-c"]
          args:
          - | {{- .Values.entrypoint | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          resources:
            {{- include "container.resources" . | nindent 12 }}
          volumeMounts:
            {{- include "container.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "container.volumes" . | nindent 8 }}
