# Use to add labels to the metadata of the resources created by this workload.
labels: {}
# Example:
# labels:
#   amd.com/label: 123

# Which model to download
modelID: TinyLlama/TinyLlama-1.1B-Chat-v1.0
modelRevision:

# Data download and preprocess script:
# This needs to be a text block of a script that downloads and preprocesses data to the /downloads/datasets/ directory.
dataScript: |
  import datasets
  dataset = datasets.load_dataset("HuggingFaceH4/ultrachat_200k", split="train_sft")
  dataset.to_json("/downloads/datasets/ultrachat_200k_train.jsonl") # Need to save any data files in this specific directory to be uploaded.

# Where the resources should be stored:
bucketModelPath: default-bucket/models/tiny-llama_tinyllama-1.1b-chat-v1.0
bucketDataDir: default-bucket/datasets/
bucketStorageHost: https://default-minio-tenant-hl.minio-tenant-default.svc.cluster.local:9000

# Download & Upload configuration:
downloadExcludeGlob: "original/*"  # Exclude things from the HuggingFace download with this
allowOverwrite: false

# Bucket credentials from a secret:
bucketCredentialsSecret:
  name: minio-credentials
  accessKeyKey: minio-access-key
  secretKeyKey: minio-secret-key

# Storage configuration:
storageClass:
storageQuantity: "10Gi"
