[tool.black]
target-version = ['py312']
line-length = 120

[tool.isort]
profile = "black"
py_version = 312
line_length = 120
known_first_party = []

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
ignore_missing_imports = true
strict = false
pretty = true
show_column_numbers = true
no_implicit_optional = false
explicit_package_bases = true
scripts_are_modules = true
check_untyped_defs = false
exclude = []
