{{- if and .Values.aimManifest.enabled (not .Values.aimManifest.serviceAccountName) .Values.aimManifest.autoApply }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-sa"
  {{- if .Values.labels }}
  labels:
    {{- range $label, $value := .Values.labels }}
    {{ $label }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
