apiVersion: v1
kind: Service
metadata:
  name: {{ include "release.fullname" . }}
  labels:
    app: {{ include "release.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.deployment.port }}
  selector:
    app: {{ include "release.fullname" . }}