# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v2
name: aimtrain-dataprep-verl
description: Dataset preprocessing job for VeRL
version: 0.1.1
appVersion: 0.6.0
maintainers:
- name: AMD
  url: https://www.amd.com/
