# general
name: "llm-inference-vllm"
namespace: "kaiwo"
username: "kaiwo"
labels_spec: {}
# image/model
image: "rocm/vllm-dev:20241205-tuned"
model: "meta-llama/Llama-3.1-8B-Instruct"
gpus: 1
# secrets: bucket storage
bucket_storage_host: https://default-minio-tenant-hl.minio-tenant-default.svc.cluster.local:9000
bucket_storage_access_key_env_spec:
  valueFrom:
    secretKeyRef:
      name: minio-credentials
      key: minio-access-key
bucket_storage_secret_key_env_spec:
  valueFrom:
    secretKeyRef:
      name: minio-credentials
      key: minio-secret-key
# secrets: huggingface token
hf_token_env_spec:
  valueFrom:
    secretKeyRef:
      name: hf-token
      key: hf-token
# storage
storage:
  quantity: "100Gi"
  storageClassName: "longhorn"
dshm:
  sizeLimit: "200Gi"
