resources:
  cpu: 32
  gpus: 4
  memory: 256Gi
workspaceReservedSize: 50Gi
downloadsReservedSize: 32Gi
checkpointsReservedSize: 512Gi

basemodelId: Wan-AI/Wan2.2-TI2V-5B
datasetId: Disney-VideoGeneration-Dataset

finetune_config:
  dataset_base_path: "/workspace/local_resources/data/Disney-VideoGeneration-Dataset"
  dataset_metadata_path: "/workspace/local_resources/data/Disney-VideoGeneration-Dataset/metadata.csv"
  height: 480
  width: 832
  num_frames: 49
  dataset_repeat: 10
  model_paths: "[[ \
    \"models/Wan-AI/Wan2.2-TI2V-5B/diffusion_pytorch_model-00001-of-00003.safetensors\", \
    \"models/Wan-AI/Wan2.2-TI2V-5B/diffusion_pytorch_model-00002-of-00003.safetensors\", \
    \"models/Wan-AI/Wan2.2-TI2V-5B/diffusion_pytorch_model-00003-of-00003.safetensors\"], \
    \"models/Wan-AI/Wan2.2-TI2V-5B/models_t5_umt5-xxl-enc-bf16.pth\", \
    \"models/Wan-AI/Wan2.2-TI2V-5B/Wan2.2_VAE.pth\"]"
  learning_rate: "1e-5"
  num_epochs: 2
  remove_prefix_in_ckpt: "pipe.dit."
  output_path: "/workspace/checkpoints/Wan2.2-TI2V-5B_full"
  trainable_models: "dit"
  architecture: "full"

interactive: false
