# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

{{- define "job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "release.fullname" . }}-job"
  {{- if .Values.labels }}
  labels:
    {{- range $label, $value := .Values.labels }}
    {{ $label }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: dataset-preprocessing
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          command:
            - /bin/bash
            - /configs/entrypoint.sh
          env:
            {{- if .Values.hfTokenSecret }}
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hfTokenSecret.name }}
                  key: {{ .Values.hfTokenSecret.key }}
            {{- end }}
            - name: BUCKET_STORAGE_HOST
              value: {{ .Values.bucketStorageHost | quote }}
            - name: BUCKET_STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketCredentialsSecret.name }}
                  key: {{ .Values.bucketCredentialsSecret.accessKeyKey }}
            - name: BUCKET_STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketCredentialsSecret.name }}
                  key: {{ .Values.bucketCredentialsSecret.secretKeyKey }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: configs
              mountPath: /configs
              readOnly: true
      volumes:
        - name: configs
          configMap:
            name: {{ include "release.fullname" . }}-configs
            defaultMode: 0775
{{- end -}}

{{- define "job_wrapped_with_kaiwojob" }}
apiVersion: kaiwo.silogen.ai/v1alpha1
kind: KaiwoJob
metadata:
  name: "{{ include "release.fullname" . }}-job"
spec:
  job:
    {{- include "job" . | nindent 4 }}
{{- end -}}

{{- if .Values.kaiwo.enabled -}}
{{- include "job_wrapped_with_kaiwojob" . }}
{{- else -}}
{{- include "job" . }}
{{- end -}}
