apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-inference-vllm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "llm-inference-vllm.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ include "llm-inference-vllm.fullname" . }}
