apiVersion: v1
kind: Service
metadata:
  name: {{ include "release.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "release.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.deployment.port }}
  selector:
    app: {{ include "release.fullname" . }}