apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dev-openvscode-server.fullname" . }}
  labels:
    app: {{ include "dev-openvscode-server.name" . }}
    {{- range .Values.labels }}
    {{ .label }}: {{ .value | quote}}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dev-openvscode-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dev-openvscode-server.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "{{ max (mul .Values.gpus 32) 4 }}Gi"
              cpu: "{{ max (mul .Values.gpus 4) 1 }}"
              {{- if .Values.gpus }}
              amd.com/gpu: "{{ .Values.gpus }}"
              {{- end }}
            limits:
              memory: "{{ max (mul .Values.gpus 32) 4 }}Gi"
              cpu: "{{ max (mul .Values.gpus 4) 1 }}"
              {{- if .Values.gpus }}
              amd.com/gpu: "{{ .Values.gpus }}"
              {{- end }}
          env:
            - name: HF_HOME
              value: /workload/.cache/huggingface
            - name: BUCKET_STORAGE_HOST
              value: {{ .Values.envVars.bucket_storage_host }}
            - name: BUCKET_STORAGE_ACCESS_KEY
              {{- toYaml .Values.envVars.bucket_storage_access_key_env_spec | nindent 14 }}
            - name: BUCKET_STORAGE_SECRET_KEY
              {{- toYaml .Values.envVars.bucket_storage_secret_key_env_spec | nindent 14 }}
            - name: HF_TOKEN
              {{- toYaml .Values.envVars.hf_token_env_spec | nindent 14 }}
          volumeMounts:
            - mountPath: /workload
              name: ephemeral-storage
            - mountPath: /workload/mounted
              name: workload-mount
            - mountPath: /dev/shm
              name: dshm
      volumes:
        # - ephemeral:
        #     volumeClaimTemplate:
        #       spec:
        #         accessModes:
        #           - ReadWriteOnce
        #         resources:
        #           requests:
        #             storage: {{ .Values.storage.quantity }}
        #         storageClassName: {{ .Values.storage.storageClassName }}
        #   name: ephemeral-storage
        - emptyDir: {}
          name: ephemeral-storage
        - configMap:
            name: {{ include "dev-openvscode-server.fullname" . }}
          name: workload-mount
        - emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.dshm.sizeLimit }}
          name: dshm
