{{- if and .Values.storage.ephemeral.storageClassName (not (and .Values.kaiwo.storageEnabled .Values.kaiwo.enabled)) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "release.fullname" . }}
spec:
  {{- if .Values.storage.ephemeral.accessModes }}
  accessModes: {{ .Values.storage.ephemeral.accessModes }}
  {{- else }}
  accessModes:
    - ReadWriteOnce
  {{- end }}
  storageClassName: {{ .Values.storage.ephemeral.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.ephemeral.quantity }}
{{- end }}
