apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-chat-app.fullname" . }}
  labels:
    app: {{ include "rag-chat-app.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ include "rag-chat-app.fullname" . }}
