inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082

default_response_timeout=3000
default_startup_timeout=500

# REMOVE THIS LINE TO ENABLE GPU METRICS WITH ANOTHER DOCKER IMAGE
disable_system_gpu_metrics=true
max_response_size=1000971520
