# Which model to download
modelID: TinyLlama/TinyLlama-1.1B-Chat-v1.0

# Where the resources should be stored:
bucketPath: default-bucket/models/TinyLlama/TinyLlama-1.1B-Chat-v1.0
bucketStorageHost: http://minio.minio-tenant-default.svc.cluster.local:80

# Download & Upload configuration:
downloadExcludeGlob: "original/*"  # Exclude things from the HuggingFace download with this
allowOverwrite: false

# Storage configuration:
storageClass: mlstorage
storageQuantity: "10Gi"

# HF Token:
hfTokenSecret:
  name: hf-token
  key: hf-token

kaiwo:
  enabled: true
