# Use e.g. for Kueue labels,
labels:
  kueue.x-k8s.io/queue-name: kaiwo

# Which model to download
modelID: TinyLlama/TinyLlama-1.1B-Chat-v1.0

# Data download and preprocess script:
dataScript: |
  import datasets
  def _argilla_message_formatter(example, idx):
      # The generation_prompt field seems to have an additional layer of list, so we take the first element.
      # Also note that this always includes an empty system prompt.
      messages = example["generation_prompt"][0]
      # There are both the "generations" and the "raw_generation_responses" fields. It seems that they contain the same content and
      # there are never actually more than one generated response per prompt. We use "generations" here because maybe it's processed with some
      # filter or something.
      messages.append({"role": "assistant", "content": example["generations"][0]})
      return {
          "dataset": "argilla-10k-mistral-large-human-prompts",
          "id": f"argilla-10k-mistral-large-human-prompts_{idx}",
          "messages": messages,
      }
  hf_id="argilla/10k_prompts_ranked_mistral_large_responses"
  dataset = datasets.load_dataset(hf_id, split="train")
  dataset = dataset.filter(lambda kind: kind == "human", input_columns="kind")
  dataset = dataset.map(_argilla_message_formatter, with_indices=True, remove_columns=dataset.column_names)
  dataset.to_json("/downloads/datasets/argilla-mistral-large-human-prompts.jsonl") # Need to save any data files in this specific directory to be uploaded.

# Where the resources should be stored:
bucketModelPath: default-bucket/models/tiny-llama_tinyllama-1.1b-chat-v1.0
bucketDataDir: default-bucket/datasets/
bucketStorageHost: https://minio.minio-tenant-default.svc.cluster.local:443

# Download & Upload configuration:
downloadExcludeGlob: "original/*"  # Exclude things from the HuggingFace download with this
allowOverwrite: false

# Bucket credentials from a secret:
bucketCredentialsSecret:
  name: minio-credentials
  accessKeyKey: API_ACCESS_KEY
  secretKeyKey: API_SECRET_KEY

# Storage configuration:
storageClass: mlstorage
storageQuantity: "10Gi"
