metadata:
  labels: {}

image: ghcr.io/silogen/openvscode-server:vllm-dev-20250124
imagePullPolicy: Always

env_vars:
  BUCKET_STORAGE_HOST: http://minio.minio-tenant-default.svc.cluster.local:80
  BUCKET_STORAGE_ACCESS_KEY:
    name: minio-credentials
    key: minio-access-key
  BUCKET_STORAGE_SECRET_KEY:
    name: minio-credentials
    key: minio-secret-key
  HF_HOME: /workload/.cache/huggingface
  # HF_TOKEN:
  #   key: hf-token
  #   name: hf-token

storage:
  ephemeral:
    quantity: 100Gi
    storageClassName: mlstorage
    accessModes:
      - ReadWriteOnce
  dshm:
    sizeLimit: 32Gi

deployment:
  port: 3000

gpus: 1
memory_per_gpu: 64  # Gi
cpu_per_gpu: 4
entrypoint: |
  bash /workload/mount/install_kubectl.sh
  bash /workload/mount/install_helm.sh
  mc alias set minio-host ${BUCKET_STORAGE_HOST} ${BUCKET_STORAGE_ACCESS_KEY} ${BUCKET_STORAGE_SECRET_KEY}
  exec ${OPENVSCODE_SERVER_ROOT}/bin/openvscode-server \
    --host 0.0.0.0 \
    --without-connection-token

# kaiwo settings (if enabled, use kaiwo CRDs to have kaiwo operator manage the workload)
kaiwo:
  enabled: false
