# secrets: bucket storage
bucket_storage:
  host: https://minio.minio-tenant-default.svc.cluster.local:443
  credentials:
    secret_name: minio-credentials
    secret_key_key: API_SECRET_KEY
    access_key_key: API_ACCESS_KEY

# secrets: huggingface token
hf_token: null

storage:
  storageClassName: mlstorage
