modelId: Wan-AI/Wan2.1-T2V-1.3B-Diffusers

entrypoint: |
  #!/bin/bash

  pip install --upgrade pip
  pip install "diffusers>=0.33" ftfy accelerate

  # --- Python: Download and save model ---
  python <<'EOF'
  import torch
  from diffusers import AutoencoderKLWan, WanPipeline
  from diffusers.schedulers.scheduling_unipc_multistep import UniPCMultistepScheduler

  flow_shift = 3.0  # 5.0 for 720P, 3.0 for 480P

  scheduler = UniPCMultistepScheduler(
      prediction_type="flow_prediction",
      use_flow_sigmas=True,
      num_train_timesteps=1000,
      flow_shift=flow_shift,
  )

  vae = AutoencoderKLWan.from_pretrained("{{ .Values.modelId }}", subfolder="vae", torch_dtype=torch.float32)
  pipe = WanPipeline.from_pretrained("{{ .Values.modelId }}", vae=vae, torch_dtype=torch.bfloat16)
  pipe.scheduler = scheduler
  pipe.save_pretrained("./Diffusion_model")
  EOF

  # --- Zip model directory ---
  cd Diffusion_model
  zip -r ../model.zip *
  cd ..

  # Upload resources
  mc cp model.zip minio-host/{{ .Values.bucketPath }}/{{ .Values.modelId }}/packaged/model.zip
