compute_environment: LOCAL_MACHINE
deepspeed_config:
  zero_stage: 1
  bf16:
    enabled: true
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
mixed_precision: bf16
num_machines: 1
num_processes: 1
use_cpu: false
