# Use a kueue:
labels:
  kueue.x-k8s.io/queue-name: kaiwo

# Bucket storage setup:
bucketStorageHost: "https://storage.googleapis.com"

# Inputs:
modelID: "yujiepan/llama-3.1-tiny-random"
bucketPath: "silogen-dev-data/models/yujiepan_llama-3.1-tiny-random"
storageQuantity: 5Gi
storageClass: mlstorage 
allowOverwrite: true
