apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials-fetcher
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-credentials
  data:
    - secretKey: API_ACCESS_KEY
      remoteRef:
        key: default-user
        property: API_ACCESS_KEY
    - secretKey: API_SECRET_KEY
      remoteRef:
        key: default-user
        property: API_SECRET_KEY
