name: Common

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-pre-commit-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check style with pre-commit
        run: pip install pre-commit && pre-commit run --all-files
