name: Copy workload documentation to public docs repo
# We rsync the docs and workloads directories to the public documentation.
# We commit and push the changes to the develop branch of the public docs
# repository. Purpose is to keep the consolidated EAI documentation updated
# with changes from the contributing repositories.

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "workloads/**"
      - ".github/workflows/docs-file-copy.yml"

jobs:
  copy-docs:
    if: github.repository == 'silogen/ai-workloads'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Push to external docs develop branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git clone https://x-access-token:${{ secrets.DOCS_REPO_TOKEN }}@github.com/silogen/ai-workloads.git source_docs
          git clone https://x-access-token:${{ secrets.DOCS_REPO_TOKEN }}@github.com/silogen/AMDEnterpriseAISuiteDocs.git target_amd_docs
          cd target_amd_docs

          rsync -av --delete --exclude='.git' ../source_docs/docs/tutorials/ docs/ai-workloads-tutorials
          rsync -av --delete --exclude='.git' ../source_docs/workloads/ docs/ai-workloads-manifests

          git add .
          git diff --staged --quiet || git commit -m "Update external docs from ai-workloads repo"
          git push origin develop
        env:
          DOCS_REPO_TOKEN: ${{ secrets.DOCS_REPO_TOKEN }}
