{{- if ne (int $.Values.nodes) 1 }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-pvc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.checkpointsReservedSize }}"
{{- end -}}
